controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_position_controller:
      type: forward_command_controller/ForwardCommandController

gripper_position_controller:
  ros__parameters:
    joints:
      - robotiq_2f_140_left_finger_joint
    interface_name: position

